### ISSUE TITLE
Support for reading directly from `pubspec.yaml`

### ISSUE THREAD

**Issue by aswinmurali-io** [aswinmurali-io/flutter_innosetup#1]
Currently flutter & vanilla dart projects that use `innosetup` package will have a `innosetup.dart` file that they execute by `dart innosetup.dart` to build the inno installer script. This is good for complex build script that requires custom build logic. But most flutter apps they don't need this approach. 

Implement support for bringing setup template directly in pubspec.yaml.

```yaml
name: innosetup  # Convert to app name
# Convert to app description
description: Make windows installer for Flutter & vanilla Dart powered apps powered by Inno Setup.  
version: 0.1.1  # Convert to app version
# Convert to app homepage
homepage: https://github.com/aswinmurali-io/flutter_innosetup

# Pubspec does not seem to use `authors` anymore. But support this anyways.
#   Dart analyse > The 'authors' field is no longer used and can be removed.
#   Try removing the field. dart(deprecated_field)
authors:
  - Author 1
  - Author 2

# Have non-pubspec conventions as advance option under `innosetup` like this.
innosetup:
  # Optional, uses no icon by default. Must be `.ico` file. Good convention is to add in `assets/` folder.
  icon: assets/icon.ico
  # Optional, uses app name as installer name by default.
  installer_name: App Windows Installer
  # Optional, defaults to true.
  run_after_install: true
  # Optional defaults to none (?). Use a simpler compression for very large apps. Decompression can get heavy.
  compression: lzma2/ultra64
  # Optional, include all languages (?).
  languages:
    - all
  # Optional, takes LICENSE file if available else no license. It's good to have a license for the software when distributing. 
  license: LICENSE
  files:
    # Optional, will automatically take build/windows/runner/$name.exe
    executable: build/windows/runner/myproject.exe
    # Optional, will automatically take build/windows/runner
    location: build/windows/runner
  # Optional, extra urls.
  publisherUrl: https://example.com/author
  supportUrl: https://example.com/support
  updatesUrl: https://example.com/updates
```
